services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: herwa-app-dev
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - analytics_db
      - redis

  db:
    image: postgres:16-alpine
    container_name: herwa-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - herwa-data-dev:/var/lib/postgresql/data
    ports:
      - "${DB_FORWARD_PORT}:5432"

  analytics_db:
    image: clickhouse/clickhouse-server:24.5-alpine
    container_name: herwa-analytics-db-dev
    restart: always
    env_file: .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - herwa-analytics-data-dev:/var/lib/clickhouse
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_NATIVE}:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    container_name: herwa-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - herwa-redis-data-dev:/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    container_name: herwa-etl-dev
    restart: always
    env_file: .env
    depends_on:
      - db
      - analytics_db
      - redis
    volumes:
      - ./crontab.dev:/var/spool/cron/crontabs/root

volumes:
  herwa-data-dev:
  herwa-analytics-data-dev:
  herwa-redis-data-dev: