services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: herwa-app-prod
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      - db
      - analytics_db
      - redis

  db:
    image: postgres:16-alpine
    container_name: herwa-db-prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - herwa-data-prod:/var/lib/postgresql/data

  analytics_db:
    image: clickhouse/clickhouse-server:24.5-alpine
    container_name: herwa-analytics-db-prod
    restart: always
    env_file: .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - herwa-analytics-data-prod:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    container_name: herwa-redis-prod
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - herwa-redis-data-prod:/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    container_name: herwa-etl-prod
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - analytics_db
      - redis

volumes:
  herwa-data-prod:
  herwa-analytics-data-prod:
  herwa-redis-data-prod: